# web: python manage.py makemigrations && echo "makemigrations" && python manage.py migrate && echo "migrate" && gunicorn zlideT2.wsgi 
web: python manage.py migrate && gunicorn zlideT2.wsgi
# web: import nltk && nltk.download('averaged_perceptron_tagger') && python manage.py migrate && gunicorn zlideT2.wsgi
